-- Grant permissions to saans_user
GRANT USAGE ON SCHEMA public TO saans_user;
GRANT CREATE ON SCHEMA public TO saans_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO saans_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO saans_user;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO saans_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO saans_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO saans_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO saans_user;
