import { Router, Request, Response, NextFunction } from 'express';
import { ReportService } from '../services/reportService.js';
import { verifyToken, isAuthenticated } from '../middleware/authMiddleware.js';
import { logger } from '../utils/logger.js';

const router = Router();

/**
 * @swagger
 * /api/reports/health:
 *   post:
 *     summary: Generate health report
 *     description: Generate comprehensive health report in specified format
 *     tags:
 *       - Reports
 *     security:
 *       - BearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               format:
 *                 type: string
 *                 enum: ['pdf', 'csv', 'json']
 *                 default: 'pdf'
 *     responses:
 *       200:
 *         description: Report generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 reportId:
 *                   type: string
 *                 downloadUrl:
 *                   type: string
 *       400:
 *         description: Invalid format
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Failed to generate report
 */
router.post('/health', verifyToken, isAuthenticated, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.userId!;
    const format = (req.body.format as 'pdf' | 'csv' | 'json') || 'pdf';
    const report = await ReportService.generateHealthReport(userId, format);
    res.json({
      success: true,
      reportId: report.id,
      downloadUrl: `/api/reports/${report.id}/download`,
    });
  } catch (error) {
    logger.error('Failed to generate health report:', error);
    res.status(500).json({ success: false, error: 'Failed to generate report' });
  }
});

/**
 * @swagger
 * /api/reports/{reportId}/download:
 *   get:
 *     summary: Download report
 *     description: Download a previously generated report
 *     tags:
 *       - Reports
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - name: reportId
 *         in: path
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Report file
 *         content:
 *           application/pdf:
 *             schema:
 *               type: string
 *               format: binary
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Report not found
 *       500:
 *         description: Failed to download report
 */
router.get('/:reportId/download', verifyToken, isAuthenticated, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.userId!;
    const reportId = req.params.reportId;
    const report = await ReportService.downloadReport(reportId, userId);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="health-report-${reportId}.pdf"`);
    res.send(report.content);
  } catch (error) {
    logger.error('Failed to download report:', error);
    res.status(500).json({ success: false, error: 'Report not found' });
  }
});

/**
 * @swagger
 * /api/reports/list:
 *   get:
 *     summary: List user reports
 *     description: Get list of all reports generated by current user
 *     tags:
 *       - Reports
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - name: limit
 *         in: query
 *         schema:
 *           type: integer
 *           default: 20
 *       - name: skip
 *         in: query
 *         schema:
 *           type: integer
 *           default: 0
 *     responses:
 *       200:
 *         description: Reports list retrieved
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Failed to fetch reports
 */
router.get('/list', verifyToken, isAuthenticated, async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.userId!;
    const reports = await ReportService.getUserReports(userId);
    res.json({
      success: true,
      data: reports,
    });
  } catch (error) {
    logger.error('Failed to fetch user reports:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch reports' });
  }
});

export default router;
